language: python

python:
  - "2.7"

env:
  -DJANGO=1.4.3

install:
  - pip -q install Django==$DJANGO
  - pip install flake8
  - pip install codecov

script:
  - flake8 webreceita --max-line-length=95
  - python webreceita/manage.py test receita
  - coverage run webreceita/manage.py test receita

after_success:
  - codecov
